# WenXin MoYun - Google Cloud Build Configuration
# This file defines the CI/CD pipeline for automatic deployment

steps:
  # Step 1: Build Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend:latest'
      - './wenxin-backend'
    waitFor: ['-']

  # Step 2: Push Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend'
    waitFor: ['build-backend']

  # Step 3: Run Database Migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'migrate-database'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a temporary Cloud Run job for migration
        gcloud run jobs create wenxin-migrate-${SHORT_SHA} \
          --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend:${SHORT_SHA} \
          --region=${_REGION} \
          --task-timeout=600 \
          --memory=1Gi \
          --cpu=1 \
          --parallelism=1 \
          --task-count=1 \
          --set-cloudsql-instances=${PROJECT_ID}:${_REGION}:${_DB_INSTANCE} \
          --set-env-vars="DATABASE_URL=postgresql+asyncpg://${_DB_USER}:${_DB_PASSWORD}@/${_DB_NAME}?host=/cloudsql/${PROJECT_ID}:${_REGION}:${_DB_INSTANCE}" \
          --command="python" \
          --args="init_db.py"
        
        # Execute migration
        gcloud run jobs execute wenxin-migrate-${SHORT_SHA} \
          --region=${_REGION} \
          --wait
        
        # Clean up migration job
        gcloud run jobs delete wenxin-migrate-${SHORT_SHA} \
          --region=${_REGION} \
          --quiet
    waitFor: ['push-backend']

  # Step 4: Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-backend'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}-api'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '300'
      - '--port'
      - '8001'
      - '--set-cloudsql-instances'
      - '${PROJECT_ID}:${_REGION}:${_DB_INSTANCE}'
      - '--update-env-vars'
      - |
        DATABASE_URL=postgresql+asyncpg://${_DB_USER}:${_DB_PASSWORD}@/${_DB_NAME}?host=/cloudsql/${PROJECT_ID}:${_REGION}:${_DB_INSTANCE},
        SECRET_KEY=${_SECRET_KEY},
        DEBUG=false,
        ENVIRONMENT=production
      - '--update-secrets'
      - |
        OPENAI_API_KEY=openai-api-key:latest,
        ANTHROPIC_API_KEY=anthropic-api-key:latest,
        GEMINI_API_KEY=gemini-api-key:latest
    waitFor: ['migrate-database']

  # Step 5: Build Frontend
  - name: 'node:18-alpine'
    id: 'build-frontend'
    dir: 'wenxin-moyun'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        npm ci --production=false
        
        echo "Building frontend..."
        VITE_API_BASE_URL=https://${_SERVICE_NAME}-api-${_CLOUD_RUN_URL_SUFFIX} \
        npm run build
        
        echo "Frontend build completed"
    waitFor: ['-']

  # Step 6: Deploy Frontend to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'deploy-frontend'
    dir: 'wenxin-moyun'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dist/'
      - 'gs://${_BUCKET_NAME}/'
    waitFor: ['build-frontend']

  # Step 7: Invalidate CDN Cache (if using Cloud CDN)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'invalidate-cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if CDN exists and invalidate cache
        if gcloud compute url-maps describe ${_SERVICE_NAME}-lb --global &>/dev/null; then
          echo "Invalidating CDN cache..."
          gcloud compute url-maps invalidate-cdn-cache ${_SERVICE_NAME}-lb \
            --path "/*" \
            --global
          echo "Cache invalidation completed"
        else
          echo "No CDN found, skipping cache invalidation"
        fi
    waitFor: ['deploy-frontend']

  # Step 8: Health Check
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Performing health checks..."
        
        # Wait for backend to be ready
        sleep 30
        
        # Check backend health
        BACKEND_URL=$(gcloud run services describe ${_SERVICE_NAME}-api --region=${_REGION} --format="value(status.url)")
        echo "Testing backend: $BACKEND_URL/health"
        curl -f "$BACKEND_URL/health" || exit 1
        
        # Check API documentation
        echo "Testing API docs: $BACKEND_URL/docs"
        curl -f "$BACKEND_URL/docs" || exit 1
        
        # Check frontend
        echo "Testing frontend: https://storage.googleapis.com/${_BUCKET_NAME}/index.html"
        curl -f "https://storage.googleapis.com/${_BUCKET_NAME}/index.html" || exit 1
        
        echo "All health checks passed!"
    waitFor: ['deploy-backend', 'deploy-frontend']

# Substitutions for build variables
substitutions:
  _REGION: 'asia-east1'
  _REPO_NAME: 'wenxin-images'
  _SERVICE_NAME: 'wenxin-moyun'
  _BUCKET_NAME: '${PROJECT_ID}-static'
  _DB_INSTANCE: 'wenxin-postgres'
  _DB_NAME: 'wenxin_db'
  _DB_USER: 'wenxin'
  _DB_PASSWORD: '${_DB_PASSWORD}'  # Set as build trigger variable
  _SECRET_KEY: '${_SECRET_KEY}'    # Set as build trigger variable
  _CLOUD_RUN_URL_SUFFIX: '${_REGION}.run.app'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  
# Build timeout
timeout: '3600s'  # 1 hour

# Images to push to registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wenxin-backend:latest'

# Build triggers
# To create the trigger, run:
# gcloud builds triggers create github \
#   --repo-name=wenxin-moyun \
#   --repo-owner=YOUR_GITHUB_USERNAME \
#   --branch-pattern="^(main|master)$" \
#   --build-config=cloudbuild.yaml \
#   --description="WenXin MoYun Production Deployment"