"""Add individual score columns and complete schema

Revision ID: 12aa0300721d
Revises: 3703a6d60754
Create Date: 2025-08-18 13:22:20.464650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12aa0300721d'
down_revision: Union[str, Sequence[str], None] = '3703a6d60754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get database dialect
    bind = op.get_bind()
    dialect_name = bind.dialect.name
    
    # Add score columns if they don't exist (for PostgreSQL)
    if dialect_name == 'postgresql':
        # Check if columns exist and add them if not
        inspector = sa.inspect(bind)
        columns = [col['name'] for col in inspector.get_columns('ai_models')]
        
        score_columns = [
            ('rhythm_score', sa.Float(), 0.0),
            ('composition_score', sa.Float(), 0.0),
            ('narrative_score', sa.Float(), 0.0),
            ('emotion_score', sa.Float(), 0.0),
            ('creativity_score', sa.Float(), 0.0),
            ('cultural_score', sa.Float(), 0.0)
        ]
        
        for col_name, col_type, default in score_columns:
            if col_name not in columns:
                op.add_column('ai_models', sa.Column(col_name, col_type, nullable=True, server_default=str(default)))
    
    # For SQLite, alter column types
    elif dialect_name == 'sqlite':
        op.alter_column('ai_models', 'rhythm_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ai_models', 'composition_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ai_models', 'narrative_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ai_models', 'emotion_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ai_models', 'creativity_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ai_models', 'cultural_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    # Drop benchmark_results column if it exists
    try:
        op.drop_column('ai_models', 'benchmark_results')
    except:
        pass  # Column might not exist
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('benchmark_results', sa.TEXT(), nullable=True))
    op.alter_column('ai_models', 'cultural_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ai_models', 'creativity_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ai_models', 'emotion_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ai_models', 'narrative_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ai_models', 'composition_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ai_models', 'rhythm_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
