"""NeedMoreEvidence — feedback protocol from Critic back to Scout.

Layer 1c: When Critic finds evidence gaps (low scores + insufficient
coverage), it generates a NeedMoreEvidence request for Scout to
perform supplementary retrieval.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class NeedMoreEvidence:
    """Request for Scout to gather supplementary evidence.

    Generated by Critic when analysis reveals evidence gaps that
    may have caused inaccurate scoring.
    """

    gaps: list[str]  # descriptions of what's missing
    suggested_queries: list[str]  # search queries for FAISS
    target_layers: list[str]  # which L-layers need more evidence
    urgency: str  # "low" | "medium" | "high"
    evidence_coverage_before: float  # coverage when gap was detected

    def to_dict(self) -> dict:
        return {
            "gaps": self.gaps,
            "suggested_queries": self.suggested_queries,
            "target_layers": self.target_layers,
            "urgency": self.urgency,
            "evidence_coverage_before": round(self.evidence_coverage_before, 4),
        }

    @classmethod
    def from_dict(cls, d: dict) -> NeedMoreEvidence:
        return cls(
            gaps=d.get("gaps", []),
            suggested_queries=d.get("suggested_queries", []),
            target_layers=d.get("target_layers", []),
            urgency=d.get("urgency", "low"),
            evidence_coverage_before=d.get("evidence_coverage_before", 0.0),
        )
