steps:
  # Run import script with Cloud SQL proxy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Python and dependencies
        apt-get update && apt-get install -y python3.11 python3-pip
        pip3 install -r requirements.txt -c constraints.txt
        
        # Download and start Cloud SQL proxy
        wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.15.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --port 5432 wenxin-moyun-prod-new:asia-east1:wenxin-postgres &
        sleep 10
        
        # Set environment for production
        export ENVIRONMENT=production
        export DATABASE_URL="postgresql+asyncpg://postgres:Qnqwdn7800@127.0.0.1:5432/wenxin"
        
        # Run the import script
        python3 production_import.py
    secretEnv: ['DB_PASSWORD']

availableSecrets:
  secretManager:
    - versionName: projects/wenxin-moyun-prod-new/secrets/db-password/versions/latest
      env: 'DB_PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: 600s