#!/usr/bin/env python3
"""Seed prototype data files for cold start.

Idempotent: skips files that already exist.
Creates:
  - app/prototype/data/skills_marketplace.jsonl
  - app/prototype/data/skills_votes.jsonl
  - app/prototype/data/feedback.jsonl
  - app/prototype/data/evolved_context.json
  - app/prototype/data/quality_baseline.json
  - app/prototype/data/sessions.jsonl  (seed digests for digestion system)
  - data/agent_logs/  (directory)
"""

import json
import os
from pathlib import Path

BASE = Path(__file__).resolve().parent

PROTO_DATA = BASE / "app" / "prototype" / "data"
AGENT_LOGS = BASE / "data" / "agent_logs"

SEED_SKILLS = [
    {"id": "1", "name": "Brand Consistency", "description": "Evaluate visual consistency with brand guidelines including logo usage, typography, and color palette adherence.", "tags": ["brand", "design"], "author": "vulca", "version": "1.0.0", "created_at": "2026-01-01T00:00:00+00:00", "upvotes": 42, "downvotes": 3},
    {"id": "2", "name": "Audience Fit", "description": "Score content for target demographic appeal across 12 audience segments with cultural sensitivity.", "tags": ["audience", "marketing"], "author": "vulca", "version": "1.0.0", "created_at": "2026-01-01T00:00:00+00:00", "upvotes": 38, "downvotes": 5},
    {"id": "3", "name": "Trend Alignment", "description": "Match against current aesthetic trends with weekly sync from design trend databases.", "tags": ["trends", "design"], "author": "vulca", "version": "1.0.0", "created_at": "2026-01-01T00:00:00+00:00", "upvotes": 29, "downvotes": 2},
    {"id": "4", "name": "Accessibility Check", "description": "Verify content meets WCAG 2.1 AA standards for color contrast, text size, and interactive elements.", "tags": ["accessibility", "quality"], "author": "community", "version": "1.0.0", "created_at": "2026-01-01T00:00:00+00:00", "upvotes": 55, "downvotes": 1},
    {"id": "5", "name": "Emotional Resonance", "description": "Analyze the emotional impact of visual content across 8 dimensions including warmth, trust, and excitement.", "tags": ["emotion", "audience"], "author": "vulca", "version": "1.0.0", "created_at": "2026-01-01T00:00:00+00:00", "upvotes": 33, "downvotes": 4},
    {"id": "6", "name": "Performance Benchmark", "description": "Measure inference latency and resource consumption for model evaluation pipelines.", "tags": ["performance", "quality"], "author": "community", "version": "1.2.0", "created_at": "2026-01-01T00:00:00+00:00", "upvotes": 21, "downvotes": 0},
]

# ---- Evolved context format matching ContextEvolver._load_context() default ----
# Uses tradition_weights keyed by tradition → {dim: weight} (not flat *_weight keys).
# Pre-populated from cultural_weights._FALLBACK_WEIGHTS so that ContextEvolver
# can boost/reduce dimensions from day one (empty weights → no evolution actions).
DEFAULT_EVOLVED_CONTEXT = {
    "tradition_weights": {
        "default": {
            "visual_perception": 0.15,
            "technical_analysis": 0.20,
            "cultural_context": 0.25,
            "critical_interpretation": 0.20,
            "philosophical_aesthetic": 0.20,
        },
        "chinese_xieyi": {
            "visual_perception": 0.10,
            "technical_analysis": 0.15,
            "cultural_context": 0.25,
            "critical_interpretation": 0.20,
            "philosophical_aesthetic": 0.30,
        },
        "chinese_gongbi": {
            "visual_perception": 0.15,
            "technical_analysis": 0.30,
            "cultural_context": 0.25,
            "critical_interpretation": 0.15,
            "philosophical_aesthetic": 0.15,
        },
        "western_academic": {
            "visual_perception": 0.20,
            "technical_analysis": 0.25,
            "cultural_context": 0.15,
            "critical_interpretation": 0.25,
            "philosophical_aesthetic": 0.15,
        },
        "islamic_geometric": {
            "visual_perception": 0.25,
            "technical_analysis": 0.30,
            "cultural_context": 0.20,
            "critical_interpretation": 0.15,
            "philosophical_aesthetic": 0.10,
        },
        "japanese_traditional": {
            "visual_perception": 0.15,
            "technical_analysis": 0.20,
            "cultural_context": 0.20,
            "critical_interpretation": 0.20,
            "philosophical_aesthetic": 0.25,
        },
        "watercolor": {
            "visual_perception": 0.20,
            "technical_analysis": 0.25,
            "cultural_context": 0.15,
            "critical_interpretation": 0.20,
            "philosophical_aesthetic": 0.20,
        },
        "african_traditional": {
            "visual_perception": 0.15,
            "technical_analysis": 0.20,
            "cultural_context": 0.30,
            "critical_interpretation": 0.20,
            "philosophical_aesthetic": 0.15,
        },
        "south_asian": {
            "visual_perception": 0.15,
            "technical_analysis": 0.20,
            "cultural_context": 0.25,
            "critical_interpretation": 0.15,
            "philosophical_aesthetic": 0.25,
        },
    },
    "version": 1,
    "evolutions": 0,
}

# ---- Seed sessions for the digestion data supply chain ----
# 15 realistic SessionDigest entries covering 9 traditions with varied scores.
# Timestamps are spaced 1 h apart starting from 2026-01-15T00:00:00 (1736899200).
_BASE_TS = 1736899200.0
SEED_SESSIONS = [
    {
        "session_id": "seed-001",
        "mode": "create",
        "intent": "mountain landscape in ink wash style",
        "tradition": "chinese_xieyi",
        "subject": "mountain landscape",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.82, "L2": 0.75, "L3": 0.88, "L4": 0.71, "L5": 0.68},
        "final_weighted_total": 0.77,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 2,
        "total_latency_ms": 45000,
        "total_cost_usd": 0.134,
        "created_at": _BASE_TS,
    },
    {
        "session_id": "seed-002",
        "mode": "create",
        "intent": "wabi-sabi ceramic bowl with crack",
        "tradition": "japanese_wabi_sabi",
        "subject": "ceramic bowl",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.91, "L2": 0.65, "L3": 0.78, "L4": 0.84, "L5": 0.59},
        "final_weighted_total": 0.75,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [{"rating": "thumbs_up"}],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 32000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 3600,
    },
    {
        "session_id": "seed-003",
        "mode": "evaluate",
        "intent": "renaissance portrait with chiaroscuro",
        "tradition": "european_renaissance",
        "subject": "portrait",
        "user_type": "human",
        "user_id": "demo-user",
        "rounds": [],
        "final_scores": {"L1": 0.73, "L2": 0.88, "L3": 0.69, "L4": 0.55, "L5": 0.81},
        "final_weighted_total": 0.73,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 28000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 7200,
    },
    {
        "session_id": "seed-004",
        "mode": "create",
        "intent": "islamic geometric tessellation pattern",
        "tradition": "islamic_geometric",
        "subject": "tessellation",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.68, "L2": 0.92, "L3": 0.55, "L4": 0.90, "L5": 0.72},
        "final_weighted_total": 0.75,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 2,
        "total_latency_ms": 51000,
        "total_cost_usd": 0.134,
        "created_at": _BASE_TS + 10800,
    },
    {
        "session_id": "seed-005",
        "mode": "create",
        "intent": "rasa-inspired dance gesture painting",
        "tradition": "indian_rasa",
        "subject": "dance gesture",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.85, "L2": 0.60, "L3": 0.93, "L4": 0.77, "L5": 0.64},
        "final_weighted_total": 0.76,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [{"rating": "thumbs_up"}],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 29000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 14400,
    },
    {
        "session_id": "seed-006",
        "mode": "create",
        "intent": "dancheong palace beam ornament",
        "tradition": "korean_dancheong",
        "subject": "beam ornament",
        "user_type": "human",
        "user_id": "demo-user",
        "rounds": [],
        "final_scores": {"L1": 0.79, "L2": 0.71, "L3": 0.66, "L4": 0.88, "L5": 0.58},
        "final_weighted_total": 0.72,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 2,
        "total_latency_ms": 47000,
        "total_cost_usd": 0.134,
        "created_at": _BASE_TS + 18000,
    },
    {
        "session_id": "seed-007",
        "mode": "evaluate",
        "intent": "ubuntu communal art sculpture",
        "tradition": "african_ubuntu",
        "subject": "communal sculpture",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.74, "L2": 0.63, "L3": 0.81, "L4": 0.69, "L5": 0.76},
        "final_weighted_total": 0.73,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [{"rating": "thumbs_down"}],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 31000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 21600,
    },
    {
        "session_id": "seed-008",
        "mode": "create",
        "intent": "persian miniature garden scene",
        "tradition": "persian_miniature",
        "subject": "garden scene",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.88, "L2": 0.79, "L3": 0.72, "L4": 0.83, "L5": 0.71},
        "final_weighted_total": 0.79,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 30000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 25200,
    },
    {
        "session_id": "seed-009",
        "mode": "create",
        "intent": "simple abstract composition",
        "tradition": "default",
        "subject": "abstract",
        "user_type": "human",
        "user_id": "demo-user",
        "rounds": [],
        "final_scores": {"L1": 0.62, "L2": 0.58, "L3": 0.71, "L4": 0.53, "L5": 0.65},
        "final_weighted_total": 0.62,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 3,
        "total_latency_ms": 62000,
        "total_cost_usd": 0.201,
        "created_at": _BASE_TS + 28800,
    },
    {
        "session_id": "seed-010",
        "mode": "create",
        "intent": "bamboo in wind ink wash",
        "tradition": "chinese_xieyi",
        "subject": "bamboo",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.78, "L2": 0.81, "L3": 0.85, "L4": 0.68, "L5": 0.72},
        "final_weighted_total": 0.77,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [{"rating": "thumbs_up"}],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 2,
        "total_latency_ms": 44000,
        "total_cost_usd": 0.134,
        "created_at": _BASE_TS + 32400,
    },
    {
        "session_id": "seed-011",
        "mode": "evaluate",
        "intent": "zen rock garden composition",
        "tradition": "japanese_wabi_sabi",
        "subject": "rock garden",
        "user_type": "human",
        "user_id": "demo-user",
        "rounds": [],
        "final_scores": {"L1": 0.86, "L2": 0.69, "L3": 0.74, "L4": 0.80, "L5": 0.55},
        "final_weighted_total": 0.73,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 27000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 36000,
    },
    {
        "session_id": "seed-012",
        "mode": "create",
        "intent": "Botticelli-style floral allegory",
        "tradition": "european_renaissance",
        "subject": "floral allegory",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.70, "L2": 0.85, "L3": 0.65, "L4": 0.48, "L5": 0.79},
        "final_weighted_total": 0.69,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [{"rating": "thumbs_down"}],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 3,
        "total_latency_ms": 68000,
        "total_cost_usd": 0.201,
        "created_at": _BASE_TS + 39600,
    },
    {
        "session_id": "seed-013",
        "mode": "create",
        "intent": "lotus pond in misty morning",
        "tradition": "chinese_xieyi",
        "subject": "lotus pond",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.80, "L2": 0.77, "L3": 0.90, "L4": 0.73, "L5": 0.70},
        "final_weighted_total": 0.78,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 2,
        "total_latency_ms": 43000,
        "total_cost_usd": 0.134,
        "created_at": _BASE_TS + 43200,
    },
    {
        "session_id": "seed-014",
        "mode": "create",
        "intent": "abstract color field meditation",
        "tradition": "default",
        "subject": "color field",
        "user_type": "agent",
        "user_id": "seed-agent",
        "rounds": [],
        "final_scores": {"L1": 0.55, "L2": 0.61, "L3": 0.68, "L4": 0.50, "L5": 0.59},
        "final_weighted_total": 0.59,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 2,
        "total_latency_ms": 48000,
        "total_cost_usd": 0.134,
        "created_at": _BASE_TS + 46800,
    },
    {
        "session_id": "seed-015",
        "mode": "create",
        "intent": "kintsugi repaired vessel still life",
        "tradition": "japanese_wabi_sabi",
        "subject": "kintsugi vessel",
        "user_type": "human",
        "user_id": "demo-user",
        "rounds": [],
        "final_scores": {"L1": 0.89, "L2": 0.72, "L3": 0.81, "L4": 0.86, "L5": 0.62},
        "final_weighted_total": 0.78,
        "best_image_url": "",
        "risk_flags": [],
        "recommendations": [],
        "feedback": [{"rating": "thumbs_up"}],
        "cultural_features": {},
        "critic_insights": [],
        "candidate_choice_index": -1,
        "time_to_select_ms": 0,
        "downloaded": False,
        "total_rounds": 1,
        "total_latency_ms": 26000,
        "total_cost_usd": 0.067,
        "created_at": _BASE_TS + 50400,
    },
]

DEFAULT_QUALITY_BASELINE = {
    "avg_score": 0.0,
    "total_evaluations": 0,
    "dimension_scores": {},
    "updated_at": None,
}


def write_jsonl(path: Path, records: list[dict]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def write_json(path: Path, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def main() -> None:
    PROTO_DATA.mkdir(parents=True, exist_ok=True)
    AGENT_LOGS.mkdir(parents=True, exist_ok=True)

    files = {
        PROTO_DATA / "skills_marketplace.jsonl": lambda p: write_jsonl(p, SEED_SKILLS),
        PROTO_DATA / "skills_votes.jsonl": lambda p: write_jsonl(p, []),
        PROTO_DATA / "skills_discussions.jsonl": lambda p: write_jsonl(p, []),
        PROTO_DATA / "skills_discussion_votes.jsonl": lambda p: write_jsonl(p, []),
        PROTO_DATA / "feedback.jsonl": lambda p: write_jsonl(p, []),
        PROTO_DATA / "evolved_context.json": lambda p: write_json(p, DEFAULT_EVOLVED_CONTEXT),
        PROTO_DATA / "quality_baseline.json": lambda p: write_json(p, DEFAULT_QUALITY_BASELINE),
        PROTO_DATA / "sessions.jsonl": lambda p: write_jsonl(p, SEED_SESSIONS),
    }

    for path, writer in files.items():
        if path.exists() and path.stat().st_size > 0:
            print(f"  SKIP {path.relative_to(BASE)} (already exists)")
        else:
            writer(path)
            print(f"  SEED {path.relative_to(BASE)}")

    print(f"  DIR  {AGENT_LOGS.relative_to(BASE)}")
    print("Done.")


if __name__ == "__main__":
    main()
