openapi: 3.0.0
info:
  title: VULCA Deep Integration API
  version: 2.0.0
  description: 47-dimension AI model evaluation system

paths:
  /v2/models/{uuid}/vulca:
    get:
      summary: Get current VULCA score for a model
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: include_perspectives
          in: query
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: VULCA score with tier-appropriate visibility
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VULCAScoreResponse'
        403:
          description: Insufficient tier for requested data
        404:
          description: Model not found

  /v2/models/{uuid}/vulca/generate:
    post:
      summary: Trigger VULCA generation (enterprise only)
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                priority:
                  type: string
                  enum: [low, normal, high]
                callback_url:
                  type: string
                  format: uri
      responses:
        202:
          description: Generation started
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    format: uuid
                  estimated_completion:
                    type: string
                    format: date-time
        403:
          description: Enterprise tier required

  /v2/vulca/algorithm-version:
    get:
      summary: Get current algorithm version information
      responses:
        200:
          description: Algorithm version details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlgorithmVersion'

  /v2/vulca/dimensions:
    get:
      summary: Get all VULCA dimension definitions
      parameters:
        - name: category
          in: query
          schema:
            type: string
            enum: [cognitive, creative, social]
      responses:
        200:
          description: List of dimension definitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DimensionDefinition'

  /v2/vulca/batch:
    post:
      summary: Get VULCA scores for multiple models
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                model_uuids:
                  type: array
                  items:
                    type: string
                    format: uuid
                  maxItems: 50
      responses:
        200:
          description: Batch VULCA scores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VULCAScoreResponse'

  /v2/vulca/leaderboard:
    get:
      summary: Get VULCA-based leaderboard
      parameters:
        - name: dimension
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
            enum: [cognitive, creative, social]
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        200:
          description: Leaderboard entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LeaderboardEntry'

  /v2/vulca/compare:
    post:
      summary: Compare multiple models across dimensions
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                model_uuids:
                  type: array
                  items:
                    type: string
                    format: uuid
                  minItems: 2
                  maxItems: 5
                dimensions:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: Comparison matrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComparisonMatrix'

components:
  schemas:
    VULCAScoreResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        model_id:
          type: string
          format: uuid
        overall_score:
          type: number
          minimum: 0
          maximum: 100
        generation_status:
          type: string
          enum: [pending, processing, completed, failed]
        dimensions:
          type: array
          items:
            $ref: '#/components/schemas/VULCADimension'
        cultural_perspectives:
          type: array
          items:
            $ref: '#/components/schemas/CulturalPerspective'
        created_at:
          type: string
          format: date-time
        tier_message:
          type: string
          description: Message for limited tier access

    VULCADimension:
      type: object
      properties:
        dimension_name:
          type: string
        display_name:
          type: string
        category:
          type: string
          enum: [cognitive, creative, social]
        value:
          type: number
          minimum: 0
          maximum: 100
        confidence:
          type: number
          minimum: 0
          maximum: 1
        description:
          type: string
        locked:
          type: boolean
          description: True if requires higher tier

    CulturalPerspective:
      type: object
      properties:
        perspective_name:
          type: string
        region_code:
          type: string
        overall_score:
          type: number
        dimension_adjustments:
          type: object
          additionalProperties:
            type: number

    DimensionDefinition:
      type: object
      properties:
        name:
          type: string
        display_name:
          type: string
        category:
          type: string
        description:
          type: string
        weight_factor:
          type: number
        tier_required:
          type: string
          enum: [free, paid, enterprise]

    LeaderboardEntry:
      type: object
      properties:
        rank:
          type: integer
        model:
          type: object
          properties:
            uuid:
              type: string
              format: uuid
            name:
              type: string
            organization:
              type: string
        score:
          type: number
        dimension_scores:
          type: object
          additionalProperties:
            type: number

    ComparisonMatrix:
      type: object
      properties:
        models:
          type: array
          items:
            type: object
            properties:
              uuid:
                type: string
              name:
                type: string
        dimensions:
          type: array
          items:
            type: string
        matrix:
          type: array
          items:
            type: array
            items:
              type: number

    AlgorithmVersion:
      type: object
      properties:
        version:
          type: string
          example: "2.0"
        name:
          type: string
          example: "EMNLP2025 Implementation"
        description:
          type: string
        is_active:
          type: boolean
        migration_date:
          type: string
          format: date-time
        deprecation_date:
          type: string
          format: date-time
          nullable: true
        algorithm_config:
          type: object
          description: Algorithm parameters and weights

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []