"""
Complete seed data for production database
Contains all 42 AI models from 15 organizations
"""
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models import AIModel


SEED_DATA = [
    # OpenAI Models (10)
    {
        "name": "GPT-4o",
        "organization": "OpenAI",
        "version": "4.0",
        "category": "multimodal",
        "description": "Most advanced multimodal model with exceptional reasoning capabilities",
        "overall_score": 94.2,
        "rhythm_score": 92.0,
        "composition_score": 95.0,
        "narrative_score": 96.0,
        "emotion_score": 93.0,
        "creativity_score": 95.0,
        "cultural_score": 91.0,
        "metrics": {"rhythm": 92, "composition": 95, "narrative": 96, "emotion": 93, "creativity": 95, "cultural": 91},
        "tags": ["Multimodal", "Reasoning", "State-of-the-art"],
        "avatar_url": "https://picsum.photos/seed/gpt4o/200/200"
    },
    {
        "name": "o1-preview",
        "organization": "OpenAI",
        "version": "1.0",
        "category": "reasoning",
        "description": "Specialized model for complex reasoning and problem-solving",
        "overall_score": 93.7,
        "rhythm_score": 85.0,
        "composition_score": 88.0,
        "narrative_score": 92.0,
        "emotion_score": 87.0,
        "creativity_score": 91.0,
        "cultural_score": 84.0,
        "metrics": {"rhythm": 85, "composition": 88, "narrative": 92, "emotion": 87, "creativity": 91, "cultural": 84},
        "tags": ["Reasoning", "Problem Solving", "Advanced"],
        "avatar_url": "https://picsum.photos/seed/o1preview/200/200"
    },
    {
        "name": "GPT-4 Turbo",
        "organization": "OpenAI", 
        "version": "4.0-turbo",
        "category": "text",
        "description": "Enhanced version of GPT-4 with improved speed and capabilities",
        "overall_score": 92.8,
        "rhythm_score": 90.0,
        "composition_score": 93.0,
        "narrative_score": 94.0,
        "emotion_score": 92.0,
        "creativity_score": 94.0,
        "cultural_score": 89.0,
        "metrics": {"rhythm": 90, "composition": 93, "narrative": 94, "emotion": 92, "creativity": 94, "cultural": 89},
        "tags": ["Text Generation", "Fast", "Versatile"],
        "avatar_url": "https://picsum.photos/seed/gpt4turbo/200/200"
    },
    {
        "name": "GPT-4",
        "organization": "OpenAI",
        "version": "4.0",
        "category": "text",
        "description": "Flagship model with strong reasoning and generation capabilities",
        "overall_score": 91.5,
        "rhythm_score": 88.0,
        "composition_score": 92.0,
        "narrative_score": 93.0,
        "emotion_score": 91.0,
        "creativity_score": 93.0,
        "cultural_score": 88.0,
        "metrics": {"rhythm": 88, "composition": 92, "narrative": 93, "emotion": 91, "creativity": 93, "cultural": 88},
        "tags": ["Text Generation", "Reasoning", "Flagship"],
        "avatar_url": "https://picsum.photos/seed/gpt4/200/200"
    },
    {
        "name": "Whisper",
        "organization": "OpenAI",
        "version": "1.0",
        "category": "audio",
        "description": "State-of-the-art speech recognition and transcription",
        "overall_score": 89.2,
        "rhythm_score": 95.0,
        "composition_score": 78.0,
        "narrative_score": 82.0,
        "emotion_score": 85.0,
        "creativity_score": 75.0,
        "cultural_score": 88.0,
        "metrics": {"rhythm": 95, "composition": 78, "narrative": 82, "emotion": 85, "creativity": 75, "cultural": 88},
        "tags": ["Audio", "Speech Recognition", "Transcription"],
        "avatar_url": "https://picsum.photos/seed/whisper/200/200"
    },
    {
        "name": "o1-mini",
        "organization": "OpenAI",
        "version": "1.0-mini",
        "category": "reasoning",
        "description": "Compact version of o1 with efficient reasoning capabilities",
        "overall_score": 88.4,
        "rhythm_score": 81.0,
        "composition_score": 84.0,
        "narrative_score": 87.0,
        "emotion_score": 83.0,
        "creativity_score": 86.0,
        "cultural_score": 80.0,
        "metrics": {"rhythm": 81, "composition": 84, "narrative": 87, "emotion": 83, "creativity": 86, "cultural": 80},
        "tags": ["Reasoning", "Efficient", "Compact"],
        "avatar_url": "https://picsum.photos/seed/o1mini/200/200"
    },
    {
        "name": "Codex",
        "organization": "OpenAI",
        "version": "1.0",
        "category": "code",
        "description": "Specialized model for code generation and understanding",
        "overall_score": 87.6,
        "rhythm_score": 80.0,
        "composition_score": 88.0,
        "narrative_score": 85.0,
        "emotion_score": 75.0,
        "creativity_score": 90.0,
        "cultural_score": 72.0,
        "metrics": {"rhythm": 80, "composition": 88, "narrative": 85, "emotion": 75, "creativity": 90, "cultural": 72},
        "tags": ["Code Generation", "Programming", "Technical"],
        "avatar_url": "https://picsum.photos/seed/codex/200/200"
    },
    {
        "name": "GPT-3.5 Turbo",
        "organization": "OpenAI",
        "version": "3.5-turbo",
        "category": "text",
        "description": "Fast and efficient model for various text generation tasks",
        "overall_score": 85.3,
        "rhythm_score": 82.0,
        "composition_score": 85.0,
        "narrative_score": 87.0,
        "emotion_score": 85.0,
        "creativity_score": 86.0,
        "cultural_score": 82.0,
        "metrics": {"rhythm": 82, "composition": 85, "narrative": 87, "emotion": 85, "creativity": 86, "cultural": 82},
        "tags": ["Text Generation", "Efficient", "Popular"],
        "avatar_url": "https://picsum.photos/seed/gpt35/200/200"
    },
    {
        "name": "DALL-E 3",
        "organization": "OpenAI",
        "version": "3.0",
        "category": "image",
        "description": "Advanced text-to-image generation with precise control",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 95.0,
        "narrative_score": 85.0,
        "emotion_score": 90.0,
        "creativity_score": 96.0,
        "cultural_score": 86.0,
        "metrics": {"rhythm": 0, "composition": 95, "narrative": 85, "emotion": 90, "creativity": 96, "cultural": 86},
        "tags": ["Image Generation", "Creative", "Precise Control"],
        "avatar_url": "https://picsum.photos/seed/dalle3/200/200"
    },
    {
        "name": "DALL-E 2",
        "organization": "OpenAI",
        "version": "2.0",
        "category": "image",
        "description": "Previous generation image model with artistic capabilities",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 90.0,
        "narrative_score": 80.0,
        "emotion_score": 85.0,
        "creativity_score": 91.0,
        "cultural_score": 82.0,
        "metrics": {"rhythm": 0, "composition": 90, "narrative": 80, "emotion": 85, "creativity": 91, "cultural": 82},
        "tags": ["Image Generation", "Artistic", "Classic"],
        "avatar_url": "https://picsum.photos/seed/dalle2/200/200"
    },
    
    # Anthropic Models (5)
    {
        "name": "Claude 3.5 Sonnet",
        "organization": "Anthropic",
        "version": "3.5",
        "category": "text",
        "description": "Most capable Claude model with enhanced reasoning and creativity",
        "overall_score": 93.8,
        "rhythm_score": 91.0,
        "composition_score": 94.0,
        "narrative_score": 96.0,
        "emotion_score": 94.0,
        "creativity_score": 95.0,
        "cultural_score": 90.0,
        "metrics": {"rhythm": 91, "composition": 94, "narrative": 96, "emotion": 94, "creativity": 95, "cultural": 90},
        "tags": ["Creative Writing", "Reasoning", "Advanced"],
        "avatar_url": "https://picsum.photos/seed/claude35/200/200"
    },
    {
        "name": "Claude 3 Opus",
        "organization": "Anthropic",
        "version": "3.0",
        "category": "multimodal",
        "description": "Powerful multimodal model with strong creative abilities",
        "overall_score": 92.5,
        "rhythm_score": 89.0,
        "composition_score": 93.0,
        "narrative_score": 95.0,
        "emotion_score": 93.0,
        "creativity_score": 94.0,
        "cultural_score": 88.0,
        "metrics": {"rhythm": 89, "composition": 93, "narrative": 95, "emotion": 93, "creativity": 94, "cultural": 88},
        "tags": ["Multimodal", "Creative", "Powerful"],
        "avatar_url": "https://picsum.photos/seed/claudeopus/200/200"
    },
    {
        "name": "Claude 3 Sonnet",
        "organization": "Anthropic",
        "version": "3.0",
        "category": "text",
        "description": "Balanced model with strong performance across tasks",
        "overall_score": 90.3,
        "rhythm_score": 87.0,
        "composition_score": 91.0,
        "narrative_score": 92.0,
        "emotion_score": 91.0,
        "creativity_score": 92.0,
        "cultural_score": 86.0,
        "metrics": {"rhythm": 87, "composition": 91, "narrative": 92, "emotion": 91, "creativity": 92, "cultural": 86},
        "tags": ["Balanced", "Versatile", "Reliable"],
        "avatar_url": "https://picsum.photos/seed/claudesonnet/200/200"
    },
    {
        "name": "Claude 2.1",
        "organization": "Anthropic",
        "version": "2.1",
        "category": "text",
        "description": "Previous generation Claude with solid capabilities",
        "overall_score": 88.1,
        "rhythm_score": 85.0,
        "composition_score": 88.0,
        "narrative_score": 90.0,
        "emotion_score": 88.0,
        "creativity_score": 89.0,
        "cultural_score": 84.0,
        "metrics": {"rhythm": 85, "composition": 88, "narrative": 90, "emotion": 88, "creativity": 89, "cultural": 84},
        "tags": ["Classic", "Reliable", "Proven"],
        "avatar_url": "https://picsum.photos/seed/claude2/200/200"
    },
    {
        "name": "Claude 3 Haiku",
        "organization": "Anthropic",
        "version": "3.0",
        "category": "text",
        "description": "Fast and efficient model for quick responses",
        "overall_score": 86.7,
        "rhythm_score": 84.0,
        "composition_score": 86.0,
        "narrative_score": 88.0,
        "emotion_score": 87.0,
        "creativity_score": 87.0,
        "cultural_score": 83.0,
        "metrics": {"rhythm": 84, "composition": 86, "narrative": 88, "emotion": 87, "creativity": 87, "cultural": 83},
        "tags": ["Fast", "Efficient", "Compact"],
        "avatar_url": "https://picsum.photos/seed/claudehaiku/200/200"
    },
    
    # Meta Models (3)
    {
        "name": "Llama 3.1 405B",
        "organization": "Meta",
        "version": "3.1",
        "category": "text",
        "description": "Meta's largest open-source model with exceptional capabilities",
        "overall_score": 93.1,
        "rhythm_score": 89.0,
        "composition_score": 92.0,
        "narrative_score": 94.0,
        "emotion_score": 91.0,
        "creativity_score": 93.0,
        "cultural_score": 87.0,
        "metrics": {"rhythm": 89, "composition": 92, "narrative": 94, "emotion": 91, "creativity": 93, "cultural": 87},
        "tags": ["Open Source", "Large Scale", "Powerful"],
        "avatar_url": "https://picsum.photos/seed/llama31/200/200"
    },
    {
        "name": "Llama 3 70B",
        "organization": "Meta",
        "version": "3.0",
        "category": "text",
        "description": "Meta's latest open-source model with strong performance",
        "overall_score": 90.7,
        "rhythm_score": 87.0,
        "composition_score": 90.0,
        "narrative_score": 92.0,
        "emotion_score": 89.0,
        "creativity_score": 91.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 87, "composition": 90, "narrative": 92, "emotion": 89, "creativity": 91, "cultural": 85},
        "tags": ["Open Source", "Latest", "Versatile"],
        "avatar_url": "https://picsum.photos/seed/llama3/200/200"
    },
    {
        "name": "Llama 2 70B",
        "organization": "Meta",
        "version": "2.0",
        "category": "text",
        "description": "Previous generation Meta model, widely adopted",
        "overall_score": 87.9,
        "rhythm_score": 84.0,
        "composition_score": 87.0,
        "narrative_score": 89.0,
        "emotion_score": 86.0,
        "creativity_score": 88.0,
        "cultural_score": 83.0,
        "metrics": {"rhythm": 84, "composition": 87, "narrative": 89, "emotion": 86, "creativity": 88, "cultural": 83},
        "tags": ["Open Source", "Proven", "Community"],
        "avatar_url": "https://picsum.photos/seed/llama2/200/200"
    },
    
    # Google Models (5)
    {
        "name": "Gemini 1.5 Pro",
        "organization": "Google",
        "version": "1.5",
        "category": "multimodal",
        "description": "Advanced multimodal model with long context window",
        "overall_score": 91.8,
        "rhythm_score": 88.0,
        "composition_score": 92.0,
        "narrative_score": 93.0,
        "emotion_score": 90.0,
        "creativity_score": 93.0,
        "cultural_score": 87.0,
        "metrics": {"rhythm": 88, "composition": 92, "narrative": 93, "emotion": 90, "creativity": 93, "cultural": 87},
        "tags": ["Multimodal", "Long Context", "Advanced"],
        "avatar_url": "https://picsum.photos/seed/gemini15/200/200"
    },
    {
        "name": "PaLM 2",
        "organization": "Google",
        "version": "2.0",
        "category": "text",
        "description": "Powerful language model with strong reasoning",
        "overall_score": 89.6,
        "rhythm_score": 86.0,
        "composition_score": 90.0,
        "narrative_score": 91.0,
        "emotion_score": 89.0,
        "creativity_score": 91.0,
        "cultural_score": 86.0,
        "metrics": {"rhythm": 86, "composition": 90, "narrative": 91, "emotion": 89, "creativity": 91, "cultural": 86},
        "tags": ["Language Model", "Reasoning", "Powerful"],
        "avatar_url": "https://picsum.photos/seed/palm2/200/200"
    },
    {
        "name": "Gemini Pro",
        "organization": "Google",
        "version": "1.0",
        "category": "text",
        "description": "Versatile model for various text tasks",
        "overall_score": 88.9,
        "rhythm_score": 85.0,
        "composition_score": 89.0,
        "narrative_score": 90.0,
        "emotion_score": 88.0,
        "creativity_score": 90.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 85, "composition": 89, "narrative": 90, "emotion": 88, "creativity": 90, "cultural": 85},
        "tags": ["Versatile", "Text Generation", "Reliable"],
        "avatar_url": "https://picsum.photos/seed/geminipro/200/200"
    },
    {
        "name": "Gemini 1.5 Flash",
        "organization": "Google",
        "version": "1.5-flash",
        "category": "multimodal",
        "description": "Fast multimodal model optimized for speed",
        "overall_score": 87.4,
        "rhythm_score": 84.0,
        "composition_score": 87.0,
        "narrative_score": 88.0,
        "emotion_score": 86.0,
        "creativity_score": 88.0,
        "cultural_score": 83.0,
        "metrics": {"rhythm": 84, "composition": 87, "narrative": 88, "emotion": 86, "creativity": 88, "cultural": 83},
        "tags": ["Fast", "Multimodal", "Efficient"],
        "avatar_url": "https://picsum.photos/seed/geminiflash/200/200"
    },
    {
        "name": "Imagen 2",
        "organization": "Google",
        "version": "2.0",
        "category": "image",
        "description": "Advanced text-to-image generation model",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 94.0,
        "narrative_score": 83.0,
        "emotion_score": 89.0,
        "creativity_score": 95.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 0, "composition": 94, "narrative": 83, "emotion": 89, "creativity": 95, "cultural": 85},
        "tags": ["Image Generation", "Advanced", "High Quality"],
        "avatar_url": "https://picsum.photos/seed/imagen2/200/200"
    },
    
    # Alibaba Models (5)
    {
        "name": "Qwen-Max",
        "organization": "Alibaba",
        "version": "1.0",
        "category": "text",
        "description": "Alibaba's most advanced language model",
        "overall_score": 91.2,
        "rhythm_score": 88.0,
        "composition_score": 91.0,
        "narrative_score": 93.0,
        "emotion_score": 90.0,
        "creativity_score": 92.0,
        "cultural_score": 89.0,
        "metrics": {"rhythm": 88, "composition": 91, "narrative": 93, "emotion": 90, "creativity": 92, "cultural": 89},
        "tags": ["Chinese", "Multilingual", "Advanced"],
        "avatar_url": "https://picsum.photos/seed/qwenmax/200/200"
    },
    {
        "name": "Qwen-Plus",
        "organization": "Alibaba",
        "version": "1.0",
        "category": "text",
        "description": "Enhanced Qwen model with improved capabilities",
        "overall_score": 89.8,
        "rhythm_score": 86.0,
        "composition_score": 89.0,
        "narrative_score": 91.0,
        "emotion_score": 89.0,
        "creativity_score": 90.0,
        "cultural_score": 88.0,
        "metrics": {"rhythm": 86, "composition": 89, "narrative": 91, "emotion": 89, "creativity": 90, "cultural": 88},
        "tags": ["Chinese", "Enhanced", "Versatile"],
        "avatar_url": "https://picsum.photos/seed/qwenplus/200/200"
    },
    {
        "name": "Qwen-72B",
        "organization": "Alibaba",
        "version": "1.0",
        "category": "text",
        "description": "Large-scale Qwen model for complex tasks",
        "overall_score": 88.5,
        "rhythm_score": 85.0,
        "composition_score": 88.0,
        "narrative_score": 90.0,
        "emotion_score": 87.0,
        "creativity_score": 89.0,
        "cultural_score": 86.0,
        "metrics": {"rhythm": 85, "composition": 88, "narrative": 90, "emotion": 87, "creativity": 89, "cultural": 86},
        "tags": ["Large Scale", "Chinese", "Open Source"],
        "avatar_url": "https://picsum.photos/seed/qwen72b/200/200"
    },
    {
        "name": "Qwen-VL",
        "organization": "Alibaba",
        "version": "1.0",
        "category": "multimodal",
        "description": "Vision-language model from Alibaba",
        "overall_score": 87.3,
        "rhythm_score": 82.0,
        "composition_score": 91.0,
        "narrative_score": 86.0,
        "emotion_score": 85.0,
        "creativity_score": 88.0,
        "cultural_score": 87.0,
        "metrics": {"rhythm": 82, "composition": 91, "narrative": 86, "emotion": 85, "creativity": 88, "cultural": 87},
        "tags": ["Multimodal", "Vision", "Chinese"],
        "avatar_url": "https://picsum.photos/seed/qwenvl/200/200"
    },
    {
        "name": "Tongyi Qianwen",
        "organization": "Alibaba",
        "version": "1.0",
        "category": "text",
        "description": "Alibaba's conversational AI model",
        "overall_score": 86.9,
        "rhythm_score": 84.0,
        "composition_score": 86.0,
        "narrative_score": 88.0,
        "emotion_score": 86.0,
        "creativity_score": 87.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 84, "composition": 86, "narrative": 88, "emotion": 86, "creativity": 87, "cultural": 85},
        "tags": ["Conversational", "Chinese", "Assistant"],
        "avatar_url": "https://picsum.photos/seed/tongyi/200/200"
    },
    
    # Baidu Models (3)
    {
        "name": "ERNIE 4.0",
        "organization": "Baidu",
        "version": "4.0",
        "category": "text",
        "description": "Baidu's latest knowledge-enhanced language model",
        "overall_score": 90.1,
        "rhythm_score": 87.0,
        "composition_score": 90.0,
        "narrative_score": 91.0,
        "emotion_score": 89.0,
        "creativity_score": 91.0,
        "cultural_score": 90.0,
        "metrics": {"rhythm": 87, "composition": 90, "narrative": 91, "emotion": 89, "creativity": 91, "cultural": 90},
        "tags": ["Knowledge Enhanced", "Chinese", "Advanced"],
        "avatar_url": "https://picsum.photos/seed/ernie4/200/200"
    },
    {
        "name": "ERNIE 3.5",
        "organization": "Baidu",
        "version": "3.5",
        "category": "text",
        "description": "Knowledge-enhanced pre-trained model",
        "overall_score": 88.7,
        "rhythm_score": 85.0,
        "composition_score": 88.0,
        "narrative_score": 89.0,
        "emotion_score": 87.0,
        "creativity_score": 89.0,
        "cultural_score": 88.0,
        "metrics": {"rhythm": 85, "composition": 88, "narrative": 89, "emotion": 87, "creativity": 89, "cultural": 88},
        "tags": ["Knowledge Enhanced", "Chinese", "Proven"],
        "avatar_url": "https://picsum.photos/seed/ernie35/200/200"
    },
    {
        "name": "ERNIE-ViLG 2.0",
        "organization": "Baidu",
        "version": "2.0",
        "category": "image",
        "description": "Text-to-image generation model with Chinese expertise",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 92.0,
        "narrative_score": 84.0,
        "emotion_score": 88.0,
        "creativity_score": 93.0,
        "cultural_score": 92.0,
        "metrics": {"rhythm": 0, "composition": 92, "narrative": 84, "emotion": 88, "creativity": 93, "cultural": 92},
        "tags": ["Image Generation", "Chinese Art", "Creative"],
        "avatar_url": "https://picsum.photos/seed/ernievilg/200/200"
    },
    
    # Mistral AI Models (2)
    {
        "name": "Mixtral 8x7B",
        "organization": "Mistral AI",
        "version": "1.0",
        "category": "text",
        "description": "Sparse mixture of experts model with strong performance",
        "overall_score": 89.4,
        "rhythm_score": 86.0,
        "composition_score": 89.0,
        "narrative_score": 90.0,
        "emotion_score": 88.0,
        "creativity_score": 90.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 86, "composition": 89, "narrative": 90, "emotion": 88, "creativity": 90, "cultural": 85},
        "tags": ["MoE", "Open Source", "Efficient"],
        "avatar_url": "https://picsum.photos/seed/mixtral/200/200"
    },
    {
        "name": "Mistral 7B",
        "organization": "Mistral AI",
        "version": "1.0",
        "category": "text",
        "description": "Compact yet powerful open-source model",
        "overall_score": 86.2,
        "rhythm_score": 83.0,
        "composition_score": 86.0,
        "narrative_score": 87.0,
        "emotion_score": 85.0,
        "creativity_score": 87.0,
        "cultural_score": 82.0,
        "metrics": {"rhythm": 83, "composition": 86, "narrative": 87, "emotion": 85, "creativity": 87, "cultural": 82},
        "tags": ["Compact", "Open Source", "Efficient"],
        "avatar_url": "https://picsum.photos/seed/mistral7b/200/200"
    },
    
    # Stability AI Models (2)
    {
        "name": "Stable Diffusion XL",
        "organization": "Stability AI",
        "version": "1.0",
        "category": "image",
        "description": "Advanced open-source text-to-image generation",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 93.0,
        "narrative_score": 82.0,
        "emotion_score": 87.0,
        "creativity_score": 94.0,
        "cultural_score": 84.0,
        "metrics": {"rhythm": 0, "composition": 93, "narrative": 82, "emotion": 87, "creativity": 94, "cultural": 84},
        "tags": ["Image Generation", "Open Source", "Popular"],
        "avatar_url": "https://picsum.photos/seed/sdxl/200/200"
    },
    {
        "name": "Stable Diffusion 2.1",
        "organization": "Stability AI",
        "version": "2.1",
        "category": "image",
        "description": "Popular open-source image generation model",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 89.0,
        "narrative_score": 78.0,
        "emotion_score": 84.0,
        "creativity_score": 90.0,
        "cultural_score": 80.0,
        "metrics": {"rhythm": 0, "composition": 89, "narrative": 78, "emotion": 84, "creativity": 90, "cultural": 80},
        "tags": ["Image Generation", "Open Source", "Community"],
        "avatar_url": "https://picsum.photos/seed/sd21/200/200"
    },
    
    # Hugging Face Model (1)
    {
        "name": "Falcon 180B",
        "organization": "Technology Innovation Institute",
        "version": "1.0",
        "category": "text",
        "description": "Large-scale open model with strong multilingual capabilities",
        "overall_score": 88.8,
        "rhythm_score": 85.0,
        "composition_score": 88.0,
        "narrative_score": 90.0,
        "emotion_score": 87.0,
        "creativity_score": 89.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 85, "composition": 88, "narrative": 90, "emotion": 87, "creativity": 89, "cultural": 85},
        "tags": ["Open Source", "Multilingual", "Large Scale"],
        "avatar_url": "https://picsum.photos/seed/falcon180b/200/200"
    },
    
    # Midjourney (1)
    {
        "name": "Midjourney V6",
        "organization": "Midjourney",
        "version": "6.0",
        "category": "image",
        "description": "Premium AI art generation with exceptional aesthetic quality",
        "overall_score": None,
        "rhythm_score": 0.0,
        "composition_score": 96.0,
        "narrative_score": 88.0,
        "emotion_score": 92.0,
        "creativity_score": 97.0,
        "cultural_score": 88.0,
        "metrics": {"rhythm": 0, "composition": 96, "narrative": 88, "emotion": 92, "creativity": 97, "cultural": 88},
        "tags": ["Image Generation", "Premium", "Artistic"],
        "avatar_url": "https://picsum.photos/seed/midjourneyv6/200/200"
    },
    
    # Cohere Models (2)
    {
        "name": "Command R+",
        "organization": "Cohere",
        "version": "1.0",
        "category": "text",
        "description": "Advanced RAG-optimized model with strong retrieval capabilities",
        "overall_score": 89.1,
        "rhythm_score": 86.0,
        "composition_score": 89.0,
        "narrative_score": 90.0,
        "emotion_score": 88.0,
        "creativity_score": 90.0,
        "cultural_score": 85.0,
        "metrics": {"rhythm": 86, "composition": 89, "narrative": 90, "emotion": 88, "creativity": 90, "cultural": 85},
        "tags": ["RAG", "Retrieval", "Enterprise"],
        "avatar_url": "https://picsum.photos/seed/commandrplus/200/200"
    },
    {
        "name": "Command R",
        "organization": "Cohere",
        "version": "1.0",
        "category": "text",
        "description": "Efficient model optimized for retrieval-augmented generation",
        "overall_score": 86.5,
        "rhythm_score": 83.0,
        "composition_score": 86.0,
        "narrative_score": 87.0,
        "emotion_score": 85.0,
        "creativity_score": 87.0,
        "cultural_score": 82.0,
        "metrics": {"rhythm": 83, "composition": 86, "narrative": 87, "emotion": 85, "creativity": 87, "cultural": 82},
        "tags": ["RAG", "Efficient", "Business"],
        "avatar_url": "https://picsum.photos/seed/commandr/200/200"
    },
    
    # DeepSeek (2)
    {
        "name": "DeepSeek Coder 33B",
        "organization": "DeepSeek",
        "version": "1.0",
        "category": "code",
        "description": "Specialized code generation model with strong programming capabilities",
        "overall_score": 88.3,
        "rhythm_score": 79.0,
        "composition_score": 90.0,
        "narrative_score": 86.0,
        "emotion_score": 74.0,
        "creativity_score": 92.0,
        "cultural_score": 73.0,
        "metrics": {"rhythm": 79, "composition": 90, "narrative": 86, "emotion": 74, "creativity": 92, "cultural": 73},
        "tags": ["Code Generation", "Programming", "Open Source"],
        "avatar_url": "https://picsum.photos/seed/deepseekcoder/200/200"
    },
    {
        "name": "DeepSeek LLM 67B",
        "organization": "DeepSeek",
        "version": "1.0",
        "category": "text",
        "description": "Large language model with strong reasoning and generation capabilities",
        "overall_score": 87.8,
        "rhythm_score": 84.0,
        "composition_score": 87.0,
        "narrative_score": 89.0,
        "emotion_score": 86.0,
        "creativity_score": 88.0,
        "cultural_score": 84.0,
        "metrics": {"rhythm": 84, "composition": 87, "narrative": 89, "emotion": 86, "creativity": 88, "cultural": 84},
        "tags": ["Language Model", "Reasoning", "Open Source"],
        "avatar_url": "https://picsum.photos/seed/deepseekllm/200/200"
    },
    
    # Yi Models (1)
    {
        "name": "Yi-34B",
        "organization": "01.AI",
        "version": "1.0",
        "category": "text",
        "description": "Bilingual model with strong Chinese and English capabilities",
        "overall_score": 87.1,
        "rhythm_score": 84.0,
        "composition_score": 86.0,
        "narrative_score": 88.0,
        "emotion_score": 86.0,
        "creativity_score": 87.0,
        "cultural_score": 87.0,
        "metrics": {"rhythm": 84, "composition": 86, "narrative": 88, "emotion": 86, "creativity": 87, "cultural": 87},
        "tags": ["Bilingual", "Chinese", "Open Source"],
        "avatar_url": "https://picsum.photos/seed/yi34b/200/200"
    }
]


async def seed_database(session: AsyncSession):
    """Seed database with initial data"""
    print(f"Seeding database with {len(SEED_DATA)} models...")
    
    for model_data in SEED_DATA:
        # Check if model already exists
        existing = await session.execute(
            select(AIModel).where(AIModel.name == model_data["name"])
        )
        if not existing.scalars().first():
            model = AIModel(**model_data)
            session.add(model)
            print(f"  Added: {model_data['name']}")
        else:
            print(f"  Skipped (exists): {model_data['name']}")
    
    await session.commit()
    print(f"Seed data loaded successfully!")